### ISSUE TITLE
smb功能能自行重新開啟嗎？

### ISSUE THREAD

**Issue by 010203le** [WhatTheBlock/Win10_Simplify#1]
您好，我想搞一個區網的硬碟共用主機，需要有軟raid和smb共用功能，不過看到您發布的版本smb是關閉的，我能自行重新打開嗎？本身巴哈帳號被永A，無法GP支持 嗚嗚嗚

**Comment by WhatTheBlock** [comment]
SMB應該可以的，我並沒有移除此組件
Win+R輸入OptionalFeatures即可開啟設定視窗
或者CMD輸入OptionalFeatures也可以
