### ISSUE TITLE
訂製系統

### ISSUE THREAD

**Issue by tsunheimat** [WhatTheBlock/Win10_Simplify#10]
需要遠程桌面, 需要smb就是連接nas的資料, 最好之持 uefi, 虛擬機安裝。 其餘盡量精簡

**Comment by tsunheimat** [comment]
Win10最新版， 不需要更新

**Comment by tsunheimat** [comment]
Hyper-v虛擬機用

**Comment by WhatTheBlock** [comment]
> Hyper-v虛擬機用

這部分要麻煩你到時候自行測試了
因為我只用VMware測試

**Comment by WhatTheBlock** [comment]
已製作完畢，正在壓縮上傳中

![Win10_21H1_19043.899_20210322.png](https://cdn.discordapp.com/attachments/507201108251508757/823581745009000458/Win10_21H1_19043.899_20210322.png)

**Comment by tsunheimat** [comment]
無法用鼠標和網卡, 而且win10 home不是不支持遠程嗎😅

**Comment by WhatTheBlock** [comment]
> 無法用鼠標和網卡, 而且win10 home不是不支持遠程嗎😅

抱歉，沒注意到 XD
我會重新製作一個，好了再通知你

**Comment by WhatTheBlock** [comment]
你好，再麻煩你試試看這個版本
[Link](http://tiny.cc/win10_21H1_20210326)

**Comment by WhatTheBlock** [comment]
> 無法用鼠標和網卡

請問這個問題是指安裝完進到桌面後，還是在PE環境下就不能使用呢？

**Comment by tsunheimat** [comment]
同安裝到安裝後都是沒有鼠標。
網卡只有傳統介面那一個，只有100m
沒有下面這個網卡
![image](https://user-images.githubusercontent.com/69157247/112708597-d1039b80-8eed-11eb-9bf2-03dacafca0bc.png)

**Comment by WhatTheBlock** [comment]
你好，本次版本將Hyper-V的所有組件&驅動都保留下來了
[Link](http://tiny.cc/win10_21H1_20210327)

**Comment by tsunheimat** [comment]
暫時沒有問題，非常感謝
