### ISSUE TITLE
Win7_Pro_(7601.24545)_x64_20210317

### ISSUE THREAD

**Issue by kissson** [WhatTheBlock/Win10_Simplify#11]
在 virtualbox 內 mount iso 之後由光驅啟動一直 100% cpu, 過不了轉轉圈, 已 disable usb, serial, audio
正確用法是什麼  ?

**Comment by WhatTheBlock** [comment]
我使用VMware測試沒有問題，VirtualBox晚點測試看看

**Comment by WhatTheBlock** [comment]
你好，剛剛測試一切正常
可以試試看我的虛擬機設定
解壓後設定正確的ISO路徑即可使用
[Link](https://github.com/WhatTheBlock/Win10_Simplify/releases/download/v2021.03.17/w7_virtualbox.rar)

**Comment by kissson** [comment]
我明天看看, 這兒已是子夜
