### ISSUE TITLE
資料夾內容 -> 共用標籤 如何打開

### ISSUE THREAD

**Issue by 010203le** [WhatTheBlock/Win10_Simplify#2]
您好，繼上次提問的smb，我又有問題需要大大幫忙了
我裝好了系統後，在共用資料夾時發現
資料夾內容沒有 共用頁籤 
想請問大大有沒有辦法打開 謝謝

**Comment by WhatTheBlock** [comment]
這個我忘記有沒有方法開啟了
如果有需要的話可以直接提出訂製要求喔
