### ISSUE TITLE
English Lang

### ISSUE THREAD

**Issue by EDK-Rise** [WhatTheBlock/Win10_Simplify#3]
Hi, 

Could you make English version of 19042.746?
you could remove calculator app and use old classic version.

**Comment by WhatTheBlock** [comment]
No problem, do you need to keep windows update?

**Comment by EDK-Rise** [comment]
No, remove All WinSxS folder. keep drivers untouched.

**Comment by WhatTheBlock** [comment]
### Your customized system is released.
### [Link](/WhatTheBlock/Win10_Simplify/blob/master/customized.md)
----
![Win10_20H2_(19042.844)_20210306_en.png](https://raw.githubusercontent.com/WhatTheBlock/Win10_Simplify/master/preview/Win10_20H2_(19042.844)_20210306_en.png)

**Comment by EDK-Rise** [comment]
Thank you.
