### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by 4dvn** [WhatTheBlock/Win10_Simplify#4]
Please create the guide of how to create windows lite using tools

**Comment by WhatTheBlock** [comment]
Sorry, there is currently no such plan.

**Comment by 4dvn** [comment]
> Sorry, there is currently no such plan.

Oh, i have another question that how to reduct the esd to ~1,5gb, thank you!

**Comment by WhatTheBlock** [comment]
> Oh, i have another question that how to reduct the esd to ~1,5gb, thank you!

Basically you need to reduce WinSxS, I recommend using WinReducer
