### ISSUE TITLE
19041.1 發現問題： chrome 同步不起做用

### ISSUE THREAD

**Issue by h223449961** [WhatTheBlock/Win10_Simplify#6]
https://github.com/WhatTheBlock/Win10_Simplify/blob/master/special_edition.md
19041.1 發現問題： chrome 同步不起做用

**Comment by WhatTheBlock** [comment]
虛擬機安裝測試一切正常

![Snipaste_2021-03-10_14-13-00.png](https://cdn.discordapp.com/attachments/507201108251508757/819090654125883412/Snipaste_2021-03-10_14-13-00.png)
