### ISSUE TITLE
19042.662 發現問題

### ISSUE THREAD

**Issue by h223449961** [WhatTheBlock/Win10_Simplify#8]
#### 大小：1.44GB
發現問題：裝不了臺灣中華民國本地語言功能

**Comment by WhatTheBlock** [comment]
請問你是想裝什麼功能呢? 手寫? 文字轉語音?
介面語言和輸入法功能都是正常的
另外，WinSxS精簡後會造成［Windows Update］、［Windows功能］功能異常
如有特殊需求請提出訂製要求，有問題、疑問請開issue就好，pull requests不是這樣用的

**Comment by h223449961** [comment]
您好！我想裝文字轉語音 請問這是有可能性的嗎？謝謝！
不好意思打擾了！如果我有特殊需要，敢請可以向您提出訂製請求嗎？感恩！


WhatTheBlock ***@***.***> 於 2021年3月11日 週四 下午9:23寫道：

**Comment by WhatTheBlock** [comment]
你選的這版本沒辦法，穩定版才可以

訂製請提供以下資料
1. 系統版本
2. 精簡程度
3. 功能要求

請將能想到所有會用到的功能都寫上，避免製作完畢又有功能想要加入，當然不侷限只寫功能，也可以說要文書處理、遊戲取向(高效能)、虛擬機多開遊戲用等等
